# Generated by Django 6.1.1 on 2026-10-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('launched', models.BooleanField(default=False)),
                ('curr_player', models.IntegerField(default=0)),
                ('curr_step', models.IntegerField(default=0)),
                ('step_start_time', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
